import { useQuery } from '@tanstack/react-query';
import { Filter, Menu, Search } from 'lucide-react-native';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View, FlatList } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { apiFetch } from '../api/client';
import { useNavigation } from '@react-navigation/native';
import { ErrorState } from '../components/ErrorState';

type Conversation = { id: string; unreadCount: number; isUnreplied: boolean; lastMessageAt: string | null; lastMessagePreview: string | null; contact: { displayName: string | null; avatarUrl: string | null }; channel: { channelName: string }; };

export function InboxScreen() {
  const insets = useSafeAreaInsets();
  const conversations = useQuery({ queryKey: ['conversations', 'open'], queryFn: () => apiFetch<{ items: Conversation[] }>('/conversations?status=OPEN&limit=25') });
  return <View style={styles.screen}><View style={styles.header}><Menu color="#23364d" size={22} /><Text style={styles.headerTitle}>Inbox</Text><View style={styles.headerActions}><Text>⇩</Text><Text>♧</Text></View></View><View style={styles.tabs}><Text style={styles.activeTab}>▤ Chats <Text style={styles.count}>{conversations.data?.items.length ?? 0}</Text></Text><Text style={styles.tab}>♧ Calls</Text></View><View style={styles.search}><Search color="#8ba2c3" size={18} /><TextInput placeholder="Search conversations..." placeholderTextColor="#8ba2c3" style={styles.input} /></View><View style={styles.filters}><Text style={styles.filterActive}>All</Text><Text>Unread</Text><Text>Closed</Text></View><View style={styles.toolbar}><Text>◯ &nbsp; Unreplied only</Text><Pressable style={styles.filterButton}><Filter color="#64748b" size={15} /><Text>Filter</Text></Pressable></View>{conversations.isLoading ? <ActivityIndicator color="#2563eb" style={styles.loader} /> : conversations.isError ? <Text style={styles.error}>Unable to load conversations.</Text> : <FlatList data={conversations.data?.items ?? []} keyExtractor={(item) => item.id} renderItem={({ item }) => <ConversationRow conversation={item} />} ListEmptyComponent={<Text style={styles.empty}>No open conversations.</Text>} />}</View>;
}

function ConversationRow({ conversation }: { conversation: Conversation }) { const navigation = useNavigation<any>(); return <Pressable onPress={() => navigation.navigate('Conversation', { conversationId: conversation.id, contactName: conversation.contact.displayName ?? 'Unknown contact' })}><View style={styles.row}><View style={styles.avatar}><Text style={styles.avatarText}>{(conversation.contact.displayName ?? '?').slice(0, 1).toUpperCase()}</Text><View style={styles.whatsapp}><Text>◉</Text></View></View><View style={styles.copy}><View style={styles.nameLine}><Text style={styles.name}>{conversation.contact.displayName ?? 'Unknown contact'}</Text>{conversation.unreadCount > 0 ? <View style={styles.unread} /> : null}<Text style={styles.time}>{formatTime(conversation.lastMessageAt)}</Text></View><Text style={styles.channel}>{conversation.channel.channelName}</Text><Text style={styles.preview}>{conversation.isUnreplied ? '↙ ' : '↗ '}{conversation.lastMessagePreview ?? 'No messages yet'}</Text></View></View></Pressable>; }
function formatTime(value: string | null) { if (!value) return ''; const hours = Math.max(1, Math.round((Date.now() - new Date(value).getTime()) / 3600000)); return hours < 24 ? `${hours}h` : `${Math.round(hours / 24)}d`; }
const styles = StyleSheet.create({ screen: { backgroundColor: '#fff', flex: 1 }, header: { alignItems: 'center', borderTopColor: '#263d44', borderTopWidth: 2, flexDirection: 'row', padding: 14 }, headerTitle: { color: '#111827', fontSize: 16, fontWeight: '600', marginLeft: 20 }, headerActions: { flexDirection: 'row', gap: 22, marginLeft: 'auto' }, tabs: { borderBottomColor: '#dce4ef', borderBottomWidth: 1, flexDirection: 'row', gap: 24, paddingHorizontal: 12 }, activeTab: { borderBottomColor: '#2563eb', borderBottomWidth: 2, color: '#1254dd', paddingBottom: 14, paddingTop: 2 }, count: { backgroundColor: '#eef4ff', borderRadius: 10, color: '#64748b', fontSize: 11, paddingHorizontal: 5 }, tab: { color: '#8ba2c3', paddingTop: 2 }, search: { alignItems: 'center', backgroundColor: '#fffaf0', borderColor: '#cfe0fa', borderRadius: 25, borderWidth: 1, flexDirection: 'row', margin: 12, paddingHorizontal: 12 }, input: { color: '#17233a', flex: 1, height: 44, marginLeft: 7 }, filters: { backgroundColor: '#f1f5f9', borderRadius: 20, flexDirection: 'row', justifyContent: 'space-around', marginHorizontal: 12, padding: 4 }, filterActive: { backgroundColor: '#fff', borderRadius: 17, color: '#17233a', fontWeight: '700', paddingHorizontal: 46, paddingVertical: 7 }, toolbar: { alignItems: 'center', borderBottomColor: '#e2e8f0', borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', padding: 12 }, filterButton: { alignItems: 'center', borderColor: '#c8dcfc', borderRadius: 18, borderWidth: 1, flexDirection: 'row', gap: 5, paddingHorizontal: 12, paddingVertical: 7 }, row: { borderBottomColor: '#e5e7eb', borderBottomWidth: 1, flexDirection: 'row', padding: 12 }, avatar: { alignItems: 'center', backgroundColor: '#f9c43d', borderRadius: 24, height: 48, justifyContent: 'center', width: 48 }, avatarText: { color: '#111827', fontSize: 18, fontWeight: '700' }, whatsapp: { backgroundColor: '#16c784', borderColor: '#fff', borderRadius: 10, borderWidth: 2, bottom: -3, color: '#fff', fontSize: 10, padding: 2, position: 'absolute', right: -2 }, copy: { flex: 1, marginLeft: 10 }, nameLine: { alignItems: 'center', flexDirection: 'row' }, name: { color: '#111827', fontSize: 15, fontWeight: '600' }, unread: { backgroundColor: '#09b57b', borderRadius: 5, height: 8, marginLeft: 8, width: 8 }, time: { color: '#64748b', fontSize: 12, marginLeft: 'auto' }, channel: { color: '#7891b5', fontSize: 12, letterSpacing: 1, marginTop: 3 }, preview: { color: '#344c70', fontSize: 14, marginTop: 7 }, loader: { marginTop: 40 }, error: { color: '#dc2626', padding: 20 }, empty: { color: '#64748b', padding: 30, textAlign: 'center' } });
