// @ts-nocheck
import * as DocumentPicker from 'expo-document-picker';
import * as ImagePicker from 'expo-image-picker';
import { Mic, Paperclip, Send, Smile, Trash2, Zap, Pause } from 'lucide-react-native';
import { useEffect, useState } from 'react';
import { Alert, Image, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

type Props = { value: string; onChange: (value: string) => void; onSend: () => void; sending?: boolean; attachment?: { uri: string; name: string; mimeType: string; type: 'IMAGE' | 'VIDEO' | 'AUDIO' | 'DOCUMENT' } | null; onAttachment?: (uri: string, name: string, mimeType: string, type: 'IMAGE' | 'VIDEO' | 'AUDIO' | 'DOCUMENT') => void; replyPreview?: { name: string; text: string } | null; onCancelReply?: () => void };
export let pendingComposerAttachment: { uri: string; name: string; mimeType: string; type: 'IMAGE' | 'VIDEO' | 'AUDIO' | 'DOCUMENT' } | null = null;
const emojis = ['😀', '😁', '😂', '🤣', '😊', '😍', '🥰', '😘', '👍', '👏', '🙏', '🔥', '❤️', '🎉', '✅', '😅', '😉', '😎', '🤔', '😭', '😮', '🙌', '💯', '✨'];

export function ConversationComposer({ value, onChange, onSend, sending, attachment: selectedAttachment, onAttachment, replyPreview, onCancelReply }: Props) {
  const [emojiOpen, setEmojiOpen] = useState(false); const [recording, setRecording] = useState(false); const [seconds, setSeconds] = useState(0); const [attachment, setAttachment] = useState<{ uri: string; name: string; image: boolean } | null>(null);
  useEffect(() => { if (!selectedAttachment) setAttachment(null); }, [selectedAttachment]);
  useEffect(() => { if (!recording) return; const timer = setInterval(() => setSeconds((current) => current + 1), 1000); return () => clearInterval(timer); }, [recording]);
  async function chooseImage() { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images', 'videos'], quality: 0.85 }); if (!result.canceled && result.assets[0]) { const asset = result.assets[0]; const name = asset.fileName ?? 'attachment'; const type = asset.type === 'video' ? 'VIDEO' : 'IMAGE'; const mimeType = asset.mimeType ?? (type === 'IMAGE' ? 'image/jpeg' : 'video/mp4'); pendingComposerAttachment = { uri: asset.uri, name, mimeType, type }; setAttachment({ uri: asset.uri, name: type === 'IMAGE' ? '' : name, image: type === 'IMAGE' }); onChange(value || '\u200B'); onAttachment?.(asset.uri, name, mimeType, type); } }
  async function chooseDocument() { const result = await DocumentPicker.getDocumentAsync({ copyToCacheDirectory: true }); if (!result.canceled) { const mimeType = result.assets[0].mimeType ?? 'application/octet-stream'; pendingComposerAttachment = { uri: result.assets[0].uri, name: result.assets[0].name, mimeType, type: 'DOCUMENT' }; setAttachment({ uri: result.assets[0].uri, name: result.assets[0].name, image: false }); onChange(value || '\u200B'); onAttachment?.(result.assets[0].uri, result.assets[0].name, mimeType, 'DOCUMENT'); } }
  function toggleRecording() { setRecording((current) => !current); setSeconds(0); }
  if (recording) return <View style={styles.recording}><Pressable onPress={() => setRecording(false)} style={styles.delete}><Trash2 color="#fff" size={17} /></Pressable><Text style={styles.recordTime}>● {`0:${String(seconds).padStart(2, '0')}`}</Text><Text style={styles.wave}>▂▅▃▇▆▃▅▇▂▆▃▅▇▂▅▃▇</Text><Pause color="#fda4af" size={18} /><Pressable onPress={() => setRecording(false)} style={styles.send}><Send color="#fff" size={18} /></Pressable></View>;
  return <><Modal visible={emojiOpen} transparent animationType="fade" onRequestClose={() => setEmojiOpen(false)}><Pressable style={styles.modalBackdrop} onPress={() => setEmojiOpen(false)}><View style={styles.emojiPanel}><TextInput placeholder="Search" placeholderTextColor="#94a3b8" style={styles.emojiSearch} /><Text style={styles.emojiHeading}>Frequently Used</Text><View style={styles.emojiGrid}>{emojis.map((emoji) => <Pressable key={emoji} onPress={() => { onChange(`${value}${emoji}`); setEmojiOpen(false); }}><Text style={styles.emoji}>{emoji}</Text></Pressable>)}</View><Text style={styles.emojiHeading}>Smileys & People</Text></View></Pressable></Modal><View style={styles.composer}>{replyPreview ? <View style={styles.replyPreview}><View style={styles.replyAccent} /><View style={styles.replyCopy}><Text style={styles.replyName}>{replyPreview.name}</Text><Text numberOfLines={1} style={styles.replyText}>{replyPreview.text}</Text></View><Pressable onPress={onCancelReply}><Text style={styles.close}>×</Text></Pressable></View> : null}{attachment ? <View style={styles.attachment}>{attachment.image ? <Image source={{ uri: attachment.uri }} style={styles.send} /> : null}<Text numberOfLines={1} style={styles.attachmentName}>{attachment.name}</Text><Pressable onPress={() => setAttachment(null)}><Text style={styles.close}>×</Text></Pressable></View> : null}<TextInput multiline value={value} onChangeText={onChange} placeholder="Write a message... use '/' for quick replies" placeholderTextColor="#a88971" style={styles.input} /><View style={styles.actions}><Pressable onPress={() => setEmojiOpen(true)}><Smile color="#64748b" size={20} /></Pressable><Pressable onPress={() => Alert.alert('Attachment', 'Choose an image or document', [{ text: 'Image', onPress: chooseImage }, { text: 'Document', onPress: chooseDocument }, { text: 'Cancel', style: 'cancel' }])}><Paperclip color="#64748b" size={20} /></Pressable><Pressable onPress={toggleRecording}><Mic color="#64748b" size={20} /></Pressable><Pressable onPress={() => onChange(`${value}/`)}><Zap color="#64748b" size={20} /></Pressable><View style={styles.spacer} /><Pressable disabled={!value.trim() || sending} onPress={onSend} style={[styles.send, value.trim() && !sending && styles.sendActive]}><Send color="#fff" size={18} /></Pressable></View></View></>;
}
const styles = StyleSheet.create({ composer: { backgroundColor: '#fff9ef', borderColor: '#cfe0fa', borderRadius: 24, borderWidth: 1, margin: 12, padding: 12 }, input: { color: '#334155', minHeight: 58, textAlignVertical: 'top' }, actions: { alignItems: 'center', flexDirection: 'row', gap: 18 }, spacer: { flex: 1 }, send: { alignItems: 'center', backgroundColor: '#b9dafa', borderRadius: 20, height: 40, justifyContent: 'center', width: 40 }, sendActive: { backgroundColor: '#2563eb' }, attachment: { alignItems: 'center', backgroundColor: '#fff', borderColor: '#cfe0fa', borderRadius: 16, flexDirection: 'row', marginBottom: 8, paddingHorizontal: 12, paddingVertical: 8 }, attachmentName: { color: '#334155', flex: 1 }, close: { color: '#64748b', fontSize: 22, marginLeft: 10 }, recording: { alignItems: 'center', backgroundColor: '#fff5f5', borderColor: '#fecaca', borderRadius: 24, borderWidth: 1, flexDirection: 'row', gap: 12, margin: 12, padding: 12 }, delete: { alignItems: 'center', backgroundColor: '#fee2e2', borderRadius: 18, height: 36, justifyContent: 'center', width: 36 }, recordTime: { color: '#17233a', fontWeight: '600' }, wave: { color: '#2563eb', flex: 1, fontSize: 13, overflow: 'hidden' }, modalBackdrop: { backgroundColor: '#0003', flex: 1, justifyContent: 'flex-end' }, emojiPanel: { backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: '55%', padding: 16 }, emojiSearch: { backgroundColor: '#f5f5f5', borderRadius: 10, color: '#17233a', height: 42, paddingHorizontal: 12 }, emojiHeading: { color: '#64748b', fontSize: 15, fontWeight: '700', marginTop: 16 }, emojiGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 14, paddingTop: 12 }, emoji: { fontSize: 28 } });
Object.assign(styles as any, {
  replyPreview: { alignItems: 'center', backgroundColor: '#f1f5f9', borderLeftColor: '#8b5cf6', borderLeftWidth: 3, flexDirection: 'row', marginBottom: 8, padding: 8 },
  replyAccent: { width: 2 },
  replyCopy: { flex: 1, marginLeft: 6 },
  replyName: { color: '#7c3aed', fontSize: 12, fontWeight: '700' },
  replyText: { color: '#64748b', fontSize: 12, marginTop: 2 },
});
