import { StyleSheet } from 'react-native';
import { fontSize, fontWeight, inputHeightDense, radius, spacing } from '../theme/tokens';
export const styles = StyleSheet.create({
  screen: { flex: 1 },
  content: { paddingBottom: spacing.xl },
  dashboardIntro: {
    borderBottomLeftRadius: radius.xxl + spacing.sm,
    borderBottomRightRadius: radius.xxl + spacing.sm,
    gap: spacing.md,
    marginBottom: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.lg,
    overflow: 'hidden',
  },
  introPatternLarge: {
    borderColor: 'rgba(255,255,255,0.48)',
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 280,
    position: 'absolute',
    right: -74,
    top: -112,
    width: 280,
  },
  introPatternSmall: {
    borderColor: 'rgba(255,255,255,0.38)',
    borderRadius: radius.pill,
    borderWidth: 1,
    height: 180,
    position: 'absolute',
    right: -25,
    top: -62,
    width: 180,
  },
  dashboardHeaderIdentity: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  greetingCopy: { flex: 1, minWidth: 0, paddingRight: spacing.md },
  greeting: { fontSize: fontSize.body, fontWeight: fontWeight.medium },
  greetingName: { fontSize: fontSize.display - spacing.xs, fontWeight: fontWeight.extrabold, letterSpacing: -0.4, marginTop: 1 },
  heroDate: { fontSize: fontSize.small - 1, marginTop: -spacing.sm },
  headerActions: { alignItems: 'center', flexDirection: 'row', gap: spacing.md - 2 },
  headerAvatar: { borderRadius: radius.pill, borderWidth: 1, padding: 2 },
  periodRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  periodCopy: { minWidth: 78 },
  periodTitle: { fontSize: fontSize.caption, fontWeight: fontWeight.bold },
  periodSubtitle: { fontSize: fontSize.tiny, marginTop: 2 },
  headerSearch: {
    alignItems: 'center',
    borderRadius: radius.xl,
    borderWidth: 1,
    flexDirection: 'row',
    height: inputHeightDense,
    paddingHorizontal: spacing.md,
  },
  searchInput: {
    flex: 1,
    fontSize: fontSize.body,
    height: inputHeightDense,
    marginLeft: spacing.sm,
  },
  clearSearch: {
    fontSize: fontSize.caption,
    fontWeight: fontWeight.semibold,
    paddingHorizontal: spacing.xs,
  },
  rangeChipRow: {
    flex: 1,
    flexDirection: 'row',
    gap: spacing.xs,
  },
  rangeChip: {
    alignItems: 'center',
    borderRadius: radius.md,
    flex: 1,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.sm + 2,
  },
  rangeChipText: {
    fontSize: fontSize.caption,
    fontWeight: fontWeight.bold,
  },

  section: {
    borderRadius: radius.xxl,
    borderWidth: 1,
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    padding: spacing.lg,
  },
  sectionHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.sm + 2, marginBottom: spacing.md + 2 },
  sectionHeaderCopy: { flex: 1, minWidth: 0 },
  sectionTitle: { fontSize: fontSize.subheading, fontWeight: fontWeight.extrabold, letterSpacing: -0.2 },
  sectionSubtitle: { fontSize: fontSize.small, lineHeight: spacing.lg, marginTop: 3 },
  usageSection: { marginHorizontal: spacing.lg, marginTop: spacing.md },
  usageSectionHeader: { marginBottom: spacing.md + 2 },

  carouselSection: {
    marginTop: spacing.xxl - 2,
  },
  carouselHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: spacing.md,
    marginBottom: spacing.md + 2,
    paddingHorizontal: spacing.lg,
  },
  carouselHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  carouselTitle: {
    fontSize: fontSize.display - spacing.xs,
    fontWeight: fontWeight.extrabold,
    letterSpacing: -0.4,
  },
  carouselSubtitle: {
    fontSize: fontSize.caption,
    marginTop: 3,
  },
  metricDeck: {
    height: 220,
    marginHorizontal: spacing.lg,
  },
  metricDeckCard: {
    alignItems: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
  },
  metricDeckSingleBack: {
    borderRadius: radius.xxl + 2,
    borderWidth: 1,
    height: 168,
    left: 8,
    position: 'absolute',
    right: 8,
  },
  metricDeckSingleBackNear: {
    top: 9,
    zIndex: 2,
  },
  metricDeckSingleBackFar: {
    top: 18,
    zIndex: 1,
  },
  metricDeckFooter: {
    alignItems: 'center',
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 4,
    position: 'absolute',
    right: 4,
  },
  metricDeckDots: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  metricDeckDot: {
    backgroundColor: '#94a3b8',
    borderRadius: 3,
    height: 5,
    opacity: 0.45,
    width: 5,
  },
  metricDeckDotActive: {
    backgroundColor: '#2563eb',
    opacity: 1,
    width: 16,
  },
  metricDeckHint: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '600',
  },
  carouselEmpty: {
    marginHorizontal: spacing.lg,
    paddingVertical: spacing.xl,
  },
  uberCard: {
    borderRadius: radius.xxl + 2,
    overflow: 'hidden',
  },
  uberPoster: {
    borderRadius: radius.xxl + 2,
    height: 168,
    justifyContent: 'space-between',
    overflow: 'hidden',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.lg,
  },
  uberHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md - 2,
  },
  uberHeaderRight: {
    alignItems: 'flex-end',
    flex: 1,
    gap: spacing.sm - 2,
    minWidth: 0,
  },
  uberFooter: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: spacing.md - 2,
    justifyContent: 'space-between',
  },
  uberFooterCopy: {
    flex: 1,
    gap: spacing.xs - 1,
    minWidth: 0,
  },
  uberOrb: {
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: radius.pill,
    position: 'absolute',
  },
  uberOrbA: {
    height: 130,
    right: -36,
    top: -44,
    width: 130,
  },
  uberOrbB: {
    bottom: -42,
    height: 110,
    left: -34,
    width: 110,
  },
  posterIconChip: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderRadius: radius.lg,
    height: spacing.xxl + spacing.md + 2,
    justifyContent: 'center',
    width: spacing.xxl + spacing.md + 2,
  },
  posterIconChipDark: {
    alignItems: 'center',
    borderRadius: radius.lg,
    height: spacing.xxl + spacing.md + 2,
    justifyContent: 'center',
    overflow: 'hidden',
    width: spacing.xxl + spacing.md + 2,
  },
  posterIconChipSoft: {
    backgroundColor: 'rgba(255,255,255,0.7)',
  },
  uberBadgeDark: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: radius.pill,
    paddingHorizontal: spacing.md - 2,
    paddingVertical: spacing.xs + 1,
  },
  uberBadgeLight: {
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderRadius: radius.pill,
    paddingHorizontal: spacing.md - 2,
    paddingVertical: spacing.xs + 1,
  },
  posterHeroLight: {
    color: '#fff',
    fontSize: fontSize.display,
    fontWeight: fontWeight.extrabold,
    letterSpacing: -0.8,
    lineHeight: spacing.xxxl,
    textAlign: 'right',
  },
  posterHeroDark: {
    color: '#0f172a',
    fontSize: fontSize.display,
    fontWeight: fontWeight.extrabold,
    letterSpacing: -0.8,
    lineHeight: spacing.xxxl,
    textAlign: 'right',
  },
  uberCardTitle: {
    color: '#0f172a',
    fontSize: fontSize.body,
    fontWeight: fontWeight.extrabold,
    letterSpacing: -0.2,
  },
  uberCardTitleLight: {
    color: '#fff',
    fontSize: fontSize.body,
    fontWeight: fontWeight.extrabold,
    letterSpacing: -0.2,
  },
  uberCardSubtitle: {
    color: '#64748b',
    fontSize: fontSize.small,
    lineHeight: spacing.lg,
  },
  uberCardSubtitleLight: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: fontSize.small,
    lineHeight: spacing.lg,
  },
  uberDelta: {
    fontSize: fontSize.small,
    fontWeight: fontWeight.bold,
  },
  deltaPositive: { color: '#059669' },
  deltaNegative: { color: '#dc2626' },
  deltaPositiveDark: { color: '#4ade80' },
  deltaNegativeDark: { color: '#fca5a5' },

  billingUsageCard: { borderRadius: radius.xl, borderWidth: StyleSheet.hairlineWidth, gap: spacing.md, overflow: 'hidden', padding: spacing.md },
  usageHero: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', minHeight: 68, paddingHorizontal: spacing.xs },
  usageHeroCopy: { flex: 1, gap: spacing.xs, minWidth: 0 },
  usageSummaryLabel: { fontSize: fontSize.caption, fontWeight: fontWeight.medium },
  usageHeroValueRow: { alignItems: 'baseline', flexDirection: 'row' },
  usageHeroValue: { fontSize: fontSize.title, fontWeight: fontWeight.bold, lineHeight: 30 },
  usageHeroLimit: { fontSize: fontSize.heading, fontWeight: fontWeight.medium },
  usageHeroRing: { alignItems: 'center', height: 58, justifyContent: 'center', marginRight: spacing.xs, width: 58 },
  usageHeroRingCenter: { alignItems: 'center', justifyContent: 'center', position: 'absolute' },
  usageHeroPercent: { fontSize: fontSize.tiny, fontWeight: fontWeight.bold },
  usageDivider: { height: StyleSheet.hairlineWidth, marginHorizontal: spacing.xs },
  usageRingsRow: { flexDirection: 'row', gap: spacing.xs, justifyContent: 'space-between' },
  usageRingItem: { alignItems: 'center', borderRadius: radius.md, flex: 1, gap: spacing.xs / 2, minWidth: 0, paddingHorizontal: 2, paddingVertical: spacing.xs },
  usageBreakdownValue: { fontSize: fontSize.caption, fontWeight: fontWeight.bold },
  usageRing: { alignItems: 'center', height: 38, justifyContent: 'center', marginTop: 1, width: 38 },
  usageRingCenter: { alignItems: 'center', justifyContent: 'center', position: 'absolute' },
  usageRingPercent: { fontSize: fontSize.tiny - 2, fontWeight: fontWeight.bold },
  usageRingLabel: { fontSize: fontSize.tiny - 1, fontWeight: fontWeight.semibold, textAlign: 'center' },
  usageRingDetail: { fontSize: fontSize.tiny - 2, fontWeight: fontWeight.medium },
  billingUsageFooter: { alignItems: 'center', alignSelf: 'flex-end', flexDirection: 'row', gap: spacing.xs / 2, marginTop: -spacing.xs },
  billingUsageFooterText: { fontSize: fontSize.tiny, fontWeight: fontWeight.semibold },

  mixLayout: { alignItems: 'center', flexDirection: 'row', gap: spacing.lg },
  donut: { alignItems: 'center', height: 120, justifyContent: 'center', position: 'relative', width: 120 },
  donutCenter: { alignItems: 'center', bottom: 0, justifyContent: 'center', left: 0, position: 'absolute', right: 0, top: 0 },
  donutValue: { fontSize: fontSize.display - spacing.xs, fontWeight: fontWeight.extrabold },
  donutLabel: { fontSize: fontSize.small - 1, fontWeight: fontWeight.semibold, marginTop: 1 },
  mixList: { flex: 1, gap: spacing.sm, minWidth: 0 },
  channelRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  channelName: { flex: 1, fontSize: fontSize.caption, fontWeight: fontWeight.semibold },
  channelPercent: { fontSize: fontSize.caption, fontWeight: fontWeight.bold, minWidth: 36, textAlign: 'right' },

  livePill: { alignItems: 'center', borderRadius: radius.pill, flexDirection: 'row', gap: spacing.xs + 1, paddingHorizontal: spacing.md - 3, paddingVertical: spacing.xs + 1 },
  liveDot: { backgroundColor: '#22c55e', borderRadius: 4, height: 7, width: 7 },
  livePillText: { fontSize: fontSize.small - 1, fontWeight: fontWeight.bold },
  statusTabsRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.md + 2,
    paddingHorizontal: spacing.lg,
  },
  statusTabChip: {
    alignItems: 'center',
    borderRadius: radius.md,
    borderWidth: 1,
    flexDirection: 'row',
    gap: spacing.xs + 2,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 1,
  },
  statusText: { fontSize: fontSize.small, fontWeight: fontWeight.bold },
  statusTextActive: { color: '#fff' },
  statusCount: { borderRadius: radius.pill, minWidth: 20, paddingHorizontal: spacing.xs + 2, paddingVertical: 1 },
  statusCountActive: { backgroundColor: 'rgba(255,255,255,0.18)' },
  statusCountText: { fontSize: fontSize.small - 1, fontWeight: fontWeight.bold, textAlign: 'center' },
  statusCountTextActive: { color: '#fff' },
  statusActive: { backgroundColor: '#2563eb', borderColor: '#2563eb' },

  memberList: { gap: spacing.md },
  memberCard: {
    borderRadius: radius.xxl,
    borderWidth: 1,
    padding: radius.lg,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.035,
    shadowRadius: 8,
    elevation: 1,
  },
  memberOffline: { opacity: 0.72 },
  memberTop: { alignItems: 'center', flexDirection: 'row', gap: spacing.md - 1 },
  memberAvatarWrap: { position: 'relative' },
  memberAvatar: { alignItems: 'center', borderRadius: radius.pill, height: 46, justifyContent: 'center', width: 46 },
  memberInitials: { fontSize: fontSize.caption, fontWeight: fontWeight.bold },
  presenceDot: { borderRadius: 6, borderWidth: 2, bottom: -1, height: 12, position: 'absolute', right: -1, width: 12 },
  memberIdentity: { flex: 1, minWidth: 0 },
  memberName: { fontSize: fontSize.small + 2, fontWeight: fontWeight.bold },
  memberActivity: { fontSize: fontSize.small, marginTop: 2 },
  presenceBadge: { borderRadius: radius.pill, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  presenceBadgeText: { fontSize: fontSize.small - 1, fontWeight: fontWeight.bold },
  memberMetrics: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.md + 2 },
  memberMetricTile: { alignItems: 'center', borderRadius: radius.md, flex: 1, minWidth: 0, paddingHorizontal: spacing.xs + 1, paddingVertical: spacing.sm },
  memberMetricValue: { fontSize: fontSize.body, fontWeight: fontWeight.extrabold },
  memberMetricLabel: { fontSize: fontSize.tiny, fontWeight: fontWeight.semibold, marginTop: 2 },
  memberBottom: { alignItems: 'center', borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: spacing.md - 2, marginTop: spacing.md, paddingTop: spacing.md - 2 },
  memberProgressWrap: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: spacing.sm, minWidth: 0 },
  memberProgressTrack: { borderRadius: radius.pill, flex: 1, height: 5, overflow: 'hidden' },
  memberProgressFill: { borderRadius: radius.pill, height: '100%' },
  memberProgressPct: { fontSize: fontSize.small, fontWeight: fontWeight.bold, minWidth: 34, textAlign: 'right' },
  responseChip: { borderRadius: radius.pill, paddingHorizontal: spacing.md - 2, paddingVertical: spacing.xs + 1 },
  responseChipText: { fontSize: fontSize.small, fontWeight: fontWeight.bold },

  liveList: { marginTop: -spacing.xs },
  liveRow: {
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: spacing.md,
    paddingVertical: spacing.md,
  },
  liveCopy: { flex: 1, minWidth: 0 },
  liveName: { fontSize: fontSize.small + 2, fontWeight: fontWeight.bold },
  liveStatusLine: { alignItems: 'center', flexDirection: 'row', gap: spacing.xs + 2, marginTop: 3 },
  toneDot: { borderRadius: 4, height: 7, width: 7 },
  liveStatus: { flex: 1, fontSize: fontSize.small },
  liveCountChip: { borderRadius: radius.sm + 2, paddingHorizontal: spacing.md - 2, paddingVertical: spacing.xs + 2 },
  liveCount: { fontSize: fontSize.small + 2, fontWeight: fontWeight.extrabold },
  loadMore: { alignItems: 'center', paddingTop: spacing.md - 2, paddingBottom: 2 },
  loadMoreText: { fontSize: fontSize.caption, fontWeight: fontWeight.bold },

  errorBox: {
    alignItems: 'center',
    borderRadius: radius.xxl,
    borderWidth: 1,
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    padding: spacing.xxl,
  },
  errorTitle: { fontSize: fontSize.subheading, fontWeight: fontWeight.extrabold },
  errorText: { fontSize: fontSize.caption, lineHeight: fontSize.heading, marginTop: spacing.xs + 2, textAlign: 'center' },
  retryBtn: {
    alignItems: 'center',
    borderRadius: radius.md,
    flexDirection: 'row',
    gap: spacing.xs + 2,
    marginTop: spacing.md + 2,
    paddingHorizontal: spacing.lg + 2,
    paddingVertical: spacing.md - 2,
  },
  retryText: { color: '#fff', fontSize: fontSize.caption, fontWeight: fontWeight.bold },
  emptyBox: {
    alignItems: 'center',
    borderRadius: radius.lg,
    borderStyle: 'dashed',
    borderWidth: 1,
    padding: spacing.xl,
  },
  emptyText: { fontSize: fontSize.caption, textAlign: 'center' },
  footerNote: { fontSize: fontSize.small - 1, lineHeight: spacing.lg, paddingHorizontal: spacing.xxl, paddingTop: spacing.lg, textAlign: 'center' },
});
