import { StyleSheet } from 'react-native';
import { fontSize, fontWeight, radius, spacing } from '../theme/tokens';
export const styles = StyleSheet.create({
  screen: { flex: 1 },
  content: { paddingBottom: spacing.xl },
  dashboardIntro: {
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    gap: spacing.md,
    marginBottom: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.lg,
    overflow: 'hidden',
  },
  introPatternLarge: {
    borderColor: 'rgba(255,255,255,0.48)',
    borderRadius: 140,
    borderWidth: 1,
    height: 280,
    position: 'absolute',
    right: -74,
    top: -112,
    width: 280,
  },
  introPatternSmall: {
    borderColor: 'rgba(255,255,255,0.38)',
    borderRadius: 90,
    borderWidth: 1,
    height: 180,
    position: 'absolute',
    right: -25,
    top: -62,
    width: 180,
  },
  dashboardHeaderIdentity: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  greetingCopy: { flex: 1, minWidth: 0, paddingRight: spacing.md },
  greeting: { fontSize: fontSize.body, fontWeight: fontWeight.medium },
  greetingName: { fontSize: 22, fontWeight: fontWeight.extrabold, letterSpacing: -0.4, marginTop: 1 },
  heroDate: { fontSize: 11, marginTop: -spacing.sm },
  headerActions: { alignItems: 'center', flexDirection: 'row', gap: 10 },
  headerAvatar: { borderRadius: 24, borderWidth: 1, padding: 2 },
  periodRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  periodCopy: { minWidth: 78 },
  periodTitle: { fontSize: fontSize.caption, fontWeight: fontWeight.bold },
  periodSubtitle: { fontSize: 10, marginTop: 2 },
  headerSearch: {
    alignItems: 'center',
    borderRadius: radius.xl,
    borderWidth: 1,
    flexDirection: 'row',
    height: 44,
    paddingHorizontal: spacing.md,
  },
  searchInput: {
    flex: 1,
    fontSize: fontSize.body,
    height: 44,
    marginLeft: spacing.sm,
  },
  clearSearch: {
    fontSize: fontSize.caption,
    fontWeight: fontWeight.semibold,
    paddingHorizontal: 4,
  },
  rangeChipRow: {
    flex: 1,
    flexDirection: 'row',
    gap: 4,
  },
  rangeChip: {
    alignItems: 'center',
    borderRadius: radius.md,
    flex: 1,
    paddingHorizontal: 5,
    paddingVertical: spacing.sm + 2,
  },
  rangeChipText: {
    fontSize: fontSize.caption,
    fontWeight: fontWeight.bold,
  },

  section: {
    borderRadius: radius.xxl,
    borderWidth: 1,
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    padding: spacing.lg,
  },
  sectionHeader: { alignItems: 'flex-start', flexDirection: 'row', gap: spacing.sm + 2, marginBottom: spacing.md + 2 },
  sectionHeaderCopy: { flex: 1, minWidth: 0 },
  sectionTitle: { fontSize: 17, fontWeight: '800', letterSpacing: -0.2 },
  sectionSubtitle: { fontSize: 12, lineHeight: 16, marginTop: 3 },
  usageSection: { marginHorizontal: spacing.lg, marginTop: spacing.md },
  usageSectionHeader: { marginBottom: spacing.md + 2 },

  carouselSection: {
    marginTop: 22,
  },
  carouselHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 14,
    paddingHorizontal: 16,
  },
  carouselHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  carouselTitle: {
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.4,
  },
  carouselSubtitle: {
    fontSize: 13,
    marginTop: 3,
  },
  metricDeck: {
    height: 220,
    marginHorizontal: 16,
  },
  metricDeckCard: {
    alignItems: 'center',
    left: 0,
    position: 'absolute',
    right: 0,
  },
  metricDeckSingleBack: {
    borderRadius: 22,
    borderWidth: 1,
    height: 168,
    left: 8,
    position: 'absolute',
    right: 8,
  },
  metricDeckSingleBackNear: {
    top: 9,
    zIndex: 2,
  },
  metricDeckSingleBackFar: {
    top: 18,
    zIndex: 1,
  },
  metricDeckFooter: {
    alignItems: 'center',
    bottom: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 4,
    position: 'absolute',
    right: 4,
  },
  metricDeckDots: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 5,
  },
  metricDeckDot: {
    backgroundColor: '#94a3b8',
    borderRadius: 3,
    height: 5,
    opacity: 0.45,
    width: 5,
  },
  metricDeckDotActive: {
    backgroundColor: '#2563eb',
    opacity: 1,
    width: 16,
  },
  metricDeckHint: {
    color: '#64748b',
    fontSize: 11,
    fontWeight: '600',
  },
  carouselEmpty: {
    marginHorizontal: 16,
    paddingVertical: 20,
  },
  uberCard: {
    borderRadius: 22,
    overflow: 'hidden',
  },
  uberPoster: {
    borderRadius: 22,
    height: 168,
    justifyContent: 'space-between',
    overflow: 'hidden',
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  uberHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  uberHeaderRight: {
    alignItems: 'flex-end',
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  uberFooter: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  uberFooterCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  uberOrb: {
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderRadius: 999,
    position: 'absolute',
  },
  uberOrbA: {
    height: 130,
    right: -36,
    top: -44,
    width: 130,
  },
  uberOrbB: {
    bottom: -42,
    height: 110,
    left: -34,
    width: 110,
  },
  posterIconChip: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderRadius: 14,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  posterIconChipDark: {
    alignItems: 'center',
    borderRadius: 14,
    height: 40,
    justifyContent: 'center',
    overflow: 'hidden',
    width: 40,
  },
  posterIconChipSoft: {
    backgroundColor: 'rgba(255,255,255,0.7)',
  },
  uberBadgeDark: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  uberBadgeLight: {
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  posterHeroLight: {
    color: '#fff',
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.8,
    lineHeight: 32,
    textAlign: 'right',
  },
  posterHeroDark: {
    color: '#0f172a',
    fontSize: 28,
    fontWeight: '800',
    letterSpacing: -0.8,
    lineHeight: 32,
    textAlign: 'right',
  },
  uberCardTitle: {
    color: '#0f172a',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  uberCardTitleLight: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  uberCardSubtitle: {
    color: '#64748b',
    fontSize: 12,
    lineHeight: 16,
  },
  uberCardSubtitleLight: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 12,
    lineHeight: 16,
  },
  uberDelta: {
    fontSize: 12,
    fontWeight: '700',
  },
  deltaPositive: { color: '#059669' },
  deltaNegative: { color: '#dc2626' },
  deltaPositiveDark: { color: '#4ade80' },
  deltaNegativeDark: { color: '#fca5a5' },

  billingUsageCard: { borderRadius: radius.xl, borderWidth: StyleSheet.hairlineWidth, gap: spacing.md, overflow: 'hidden', padding: spacing.md },
  usageHero: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', minHeight: 68, paddingHorizontal: spacing.xs },
  usageHeroCopy: { flex: 1, gap: spacing.xs, minWidth: 0 },
  usageSummaryLabel: { fontSize: fontSize.caption, fontWeight: fontWeight.medium },
  usageHeroValueRow: { alignItems: 'baseline', flexDirection: 'row' },
  usageHeroValue: { fontSize: fontSize.title, fontWeight: fontWeight.bold, lineHeight: 30 },
  usageHeroLimit: { fontSize: fontSize.heading, fontWeight: fontWeight.medium },
  usageHeroRing: { alignItems: 'center', height: 58, justifyContent: 'center', marginRight: spacing.xs, width: 58 },
  usageHeroRingCenter: { alignItems: 'center', justifyContent: 'center', position: 'absolute' },
  usageHeroPercent: { fontSize: fontSize.tiny, fontWeight: fontWeight.bold },
  usageDivider: { height: StyleSheet.hairlineWidth, marginHorizontal: spacing.xs },
  usageRingsRow: { flexDirection: 'row', gap: spacing.xs, justifyContent: 'space-between' },
  usageRingItem: { alignItems: 'center', borderRadius: radius.md, flex: 1, gap: 2, minWidth: 0, paddingHorizontal: 2, paddingVertical: spacing.xs },
  usageBreakdownValue: { fontSize: fontSize.caption, fontWeight: fontWeight.bold },
  usageRing: { alignItems: 'center', height: 38, justifyContent: 'center', marginTop: 1, width: 38 },
  usageRingCenter: { alignItems: 'center', justifyContent: 'center', position: 'absolute' },
  usageRingPercent: { fontSize: 8, fontWeight: fontWeight.bold },
  usageRingLabel: { fontSize: 9, fontWeight: fontWeight.semibold, textAlign: 'center' },
  usageRingDetail: { fontSize: 8, fontWeight: fontWeight.medium },
  billingUsageFooter: { alignItems: 'center', alignSelf: 'flex-end', flexDirection: 'row', gap: 2, marginTop: -spacing.xs },
  billingUsageFooterText: { fontSize: fontSize.tiny, fontWeight: fontWeight.semibold },

  mixLayout: { alignItems: 'center', flexDirection: 'row', gap: 16 },
  donut: { alignItems: 'center', height: 120, justifyContent: 'center', position: 'relative', width: 120 },
  donutCenter: { alignItems: 'center', bottom: 0, justifyContent: 'center', left: 0, position: 'absolute', right: 0, top: 0 },
  donutValue: { fontSize: 22, fontWeight: '800' },
  donutLabel: { fontSize: 11, fontWeight: '600', marginTop: 1 },
  mixList: { flex: 1, gap: 8, minWidth: 0 },
  channelRow: { alignItems: 'center', flexDirection: 'row', gap: 8 },
  channelName: { flex: 1, fontSize: 13, fontWeight: '600' },
  channelPercent: { fontSize: 13, fontWeight: '700', minWidth: 36, textAlign: 'right' },

  livePill: { alignItems: 'center', borderRadius: 999, flexDirection: 'row', gap: 5, paddingHorizontal: 9, paddingVertical: 5 },
  liveDot: { backgroundColor: '#22c55e', borderRadius: 4, height: 7, width: 7 },
  livePillText: { fontSize: 11, fontWeight: '700' },
  statusTabsRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 14,
    paddingHorizontal: 16,
  },
  statusTabChip: {
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  statusText: { fontSize: 12, fontWeight: '700' },
  statusTextActive: { color: '#fff' },
  statusCount: { borderRadius: 999, minWidth: 20, paddingHorizontal: 6, paddingVertical: 1 },
  statusCountActive: { backgroundColor: 'rgba(255,255,255,0.18)' },
  statusCountText: { fontSize: 11, fontWeight: '700', textAlign: 'center' },
  statusCountTextActive: { color: '#fff' },
  statusActive: { backgroundColor: '#2563eb', borderColor: '#2563eb' },

  memberList: { gap: 12 },
  memberCard: {
    borderRadius: 20,
    borderWidth: 1,
    padding: 14,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.035,
    shadowRadius: 8,
    elevation: 1,
  },
  memberOffline: { opacity: 0.72 },
  memberTop: { alignItems: 'center', flexDirection: 'row', gap: 11 },
  memberAvatarWrap: { position: 'relative' },
  memberAvatar: { alignItems: 'center', borderRadius: 23, height: 46, justifyContent: 'center', width: 46 },
  memberInitials: { fontSize: 13, fontWeight: '700' },
  presenceDot: { borderRadius: 6, borderWidth: 2, bottom: -1, height: 12, position: 'absolute', right: -1, width: 12 },
  memberIdentity: { flex: 1, minWidth: 0 },
  memberName: { fontSize: 14, fontWeight: '700' },
  memberActivity: { fontSize: 12, marginTop: 2 },
  presenceBadge: { borderRadius: 999, paddingHorizontal: 8, paddingVertical: 4 },
  presenceBadgeText: { fontSize: 11, fontWeight: '700' },
  memberMetrics: { flexDirection: 'row', gap: 8, marginTop: 14 },
  memberMetricTile: { alignItems: 'center', borderRadius: 12, flex: 1, minWidth: 0, paddingHorizontal: 5, paddingVertical: 8 },
  memberMetricValue: { fontSize: 15, fontWeight: '800' },
  memberMetricLabel: { fontSize: 10, fontWeight: '600', marginTop: 2 },
  memberBottom: { alignItems: 'center', borderTopWidth: StyleSheet.hairlineWidth, flexDirection: 'row', gap: 10, marginTop: 12, paddingTop: 10 },
  memberProgressWrap: { alignItems: 'center', flex: 1, flexDirection: 'row', gap: 8, minWidth: 0 },
  memberProgressTrack: { borderRadius: 999, flex: 1, height: 5, overflow: 'hidden' },
  memberProgressFill: { borderRadius: 999, height: '100%' },
  memberProgressPct: { fontSize: 12, fontWeight: '700', minWidth: 34, textAlign: 'right' },
  responseChip: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 5 },
  responseChipText: { fontSize: 12, fontWeight: '700' },

  liveList: { marginTop: -4 },
  liveRow: {
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 12,
  },
  liveCopy: { flex: 1, minWidth: 0 },
  liveName: { fontSize: 14, fontWeight: '700' },
  liveStatusLine: { alignItems: 'center', flexDirection: 'row', gap: 6, marginTop: 3 },
  toneDot: { borderRadius: 4, height: 7, width: 7 },
  liveStatus: { flex: 1, fontSize: 12 },
  liveCountChip: { borderRadius: 10, paddingHorizontal: 10, paddingVertical: 6 },
  liveCount: { fontSize: 14, fontWeight: '800' },
  loadMore: { alignItems: 'center', paddingTop: 10, paddingBottom: 2 },
  loadMoreText: { fontSize: 13, fontWeight: '700' },

  errorBox: {
    alignItems: 'center',
    borderRadius: 20,
    borderWidth: 1,
    marginHorizontal: 16,
    marginTop: 12,
    padding: 24,
  },
  errorTitle: { fontSize: 17, fontWeight: '800' },
  errorText: { fontSize: 13, lineHeight: 18, marginTop: 6, textAlign: 'center' },
  retryBtn: {
    alignItems: 'center',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 6,
    marginTop: 14,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  retryText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  emptyBox: {
    alignItems: 'center',
    borderRadius: 14,
    borderStyle: 'dashed',
    borderWidth: 1,
    padding: 20,
  },
  emptyText: { fontSize: 13, textAlign: 'center' },
  footerNote: { fontSize: 11, lineHeight: 16, paddingHorizontal: 24, paddingTop: 16, textAlign: 'center' },
});
